sonar.projectKey=espectro0_rutadeorigen_processor
sonar.organization=espectro0
sonar.projectName=rutadeorigen - processor

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
