image:
  repository: ghcr.io/espectro0/rutadeorigen
  pullPolicy: IfNotPresent

port: 8080

logLevel: info

terminationGracePeriodSeconds: 20

probes:
  startup:
    periodSeconds: 2
    failureThreshold: 15
  liveness:
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    periodSeconds: 5
    failureThreshold: 2
    timeoutSeconds: 3

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi

services: {}