{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: rutadeorigen
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/part-of: rutadeorigen
    spec:
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds  }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.image.repository }}/{{ $name }}:{{ required (printf "missing services.%s.tag" $name) $svc.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.port }}
          env:
            - name: SERVICE_NAME
              value: {{ $name | quote }}
            - name: PORT
              value: {{ $.Values.port | quote }}
            - name: LOG_LEVEL
              value: {{ $svc.logLevel | default $.Values.logLevel | quote }}
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: {{ $.Values.probes.startup.periodSeconds }}
            failureThreshold: {{ $.Values.probes.startup.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: {{ $.Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ $.Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: {{ $.Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ $.Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ $.Values.probes.readiness.timeoutSeconds }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
{{- end }}