version: 3
workdir: .

allow:
  depOnAnyVendor: false
  ignoreNotFoundComponents: true

excludeFiles:
  - "^.*_test\\.go$"

components:
  main:           { in: [cmd/**] }
  domain:         { in: [internal/domain, internal/domain/**] }
  dto:            { in: [internal/application/input/dto/**] }
  inputPorts:     { in: [internal/application/input/ports, internal/application/input/ports/**] }
  inputAdapters:  { in: [internal/application/input/adapters, internal/application/input/adapters/**] }
  usecases:       { in: [internal/application/usecases, internal/application/usecases/**] }
  outputPorts:    { in: [internal/application/output/ports, internal/application/output/ports/**] }
  infraInput:     { in: [internal/infrastructure/input/**] }
  infraOutput:    { in: [internal/infrastructure/output/**] }
  platform:       { in: [internal/platform, internal/platform/**] }

deps:

  domain:
    mayDependOn: [domain]

  dto:
    mayDependOn: [dto]

  outputPorts:
    mayDependOn: [outputPorts, domain]

  usecases:
    mayDependOn: [usecases, domain, outputPorts]

  inputPorts:
    mayDependOn: [inputPorts, dto]

  inputAdapters:
    mayDependOn: [inputAdapters, inputPorts, dto, usecases, domain]

  infraInput:
    anyVendorDeps: true
    mayDependOn: [infraInput, inputPorts, dto, platform]

  infraOutput:
    anyVendorDeps: true
    mayDependOn: [infraOutput, outputPorts, domain, platform]

  platform:
    anyVendorDeps: true
    mayDependOn: [platform]

  main:
    anyVendorDeps: true
    anyProjectDeps: true
