sonar.projectKey=espectro0_rutadeorigen_qr
sonar.organization=espectro0
sonar.projectName=rutadeorigen - qr

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.coverage.exclusions=cmd/**
sonar.go.coverage.reportPaths=coverage.out
