sonar.projectKey=Espectro0_rutadeorigen_rutadeorigen_qr
sonar.organization=Espectro0_rutadeorigen
sonar.projectName=rutadeorigen - qr

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
