name: processor

on:
  pull_request:
    paths:
      - "services/processor/**"
      - ".github/workflows/_go-service.yml"
      - ".golangci.yml"
      - "go.work"
      - "lib/**"
      - ".dockerignore"
  push:
    branches: [main]
    paths:
      - "services/processor/**"
      - ".github/workflows/_go-service.yml"
      - ".golangci.yml"
      - "go.work"
      - "lib/**"
      - ".dockerignore"

jobs:
  ci:
    name: processor
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_go-service.yml
    with:
      service: processor
      build-image: true
    secrets: inherit