name: traceability

on:
  pull_request:
    paths:
      - "services/traceability/**"
      - ".github/workflows/_go-service.yml"
      - ".golangci.yml"
      - "go.work"
      - "lib/**"
      - ".dockerignore"
  push:
    branches: [main]
    paths:
      - "services/traceability/**"
      - ".github/workflows/_go-service.yml"
      - ".golangci.yml"
      - "go.work"
      - "lib/**"
      - ".dockerignore"

jobs:
  ci:
    uses: ./.github/workflows/_go-service.yml
    with:
      service: traceability
      build-image: true
    secrets: inherit